# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maththeory',
            name='task',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theorydiscretmath',
            name='ask',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theoryhightermath',
            name='ask',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theorytheoryofprobabilty',
            name='ask',
            field=models.TextField(blank=True),
        ),
    ]
