# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Theory', '0002_auto_20170318_2213'),
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathtask',
            name='title',
        ),
        migrations.AddField(
            model_name='mathtask',
            name='Theor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Теория', to='Theory.MathTheory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathtask',
            name='tasks',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
