# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization', '0002_auto_20170321_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='no_avatar.png', upload_to='profile_images'),
        ),
    ]
